export const nodeConstants = {
  GET_NODETYPE_REQUEST: "NODES_GETTYPE_REQUEST",
  GET_NODETYPE_SUCCESS: "NODES_GETTYPE_SUCCESS",
  GET_NODETYPE_FAILURE: "NODES_GETTYPE_FAILURE",

  GET_NODETOTAL_REQUEST: "NODES_GETTOTAL_REQUEST",
  GET_NODETOTAL_SUCCESS: "NODES_GETTOTAL_SUCCESS",
  GET_NODETOTAL_FAILURE: "NODES_GETTOTAL_FAILURE",

  GET_NODECOUNTRY_REQUEST: "NODES_GETCOUNTRY_REQUEST",
  GET_NODECOUNTRY_SUCCESS: "NODES_GETCOUNTRY_SUCCESS",
  GET_NODECOUNTRY_FAILURE: "NODES_GETCOUNTRY_FAILURE",

  GET_NODETOTALBYABROAD_REQUEST: "NODES_GETTOTALBYABROAD_REQUEST",
  GET_NODETOTALBYABROAD_SUCCESS: "NODES_GETTOTALBYABROAD_SUCCESS",
  GET_NODETOTALBYABROAD_FAILURE: "NODES_GETTOTALBYABROAD_FAILURE",

  GET_UPDATETIME_REQUEST: "NODES_GETUPDATEIME_REQUEST",
  GET_UPDATETIME_SUCCESSS: "NODES_GETUPDATETIME_SUCCESS",
  GET_UPDATETIME_FAILURE: "NODES_GETUPDATETIME_FAILURE",

  SET_UPDATETIME_REQUEST: "NODES_UPDATETIME_REQUEST",
  SET_UPDATETIME_SUCCESS: "NODES_UPDATETIME_SUCCESS",
  SET_UPDATETIME_FAILURE: "NODES_UPDATETIME_FAILURE",
};
