export const DataBaseConstants = {
  CREATE_REQUEST: "DATABASE_CREATE_REQUEST",
  CREATE_SUCCESS: "DATABASE_CREATE_SUCCESS",
  CREATE_FAILURE: "DATABASE_CREATE_FAILURE",

  UPDATE_REQUEST: "DATABASE_UPDATE_REQUEST",
  UPDATE_SUCCESS: "DATABASE_UPDATE_SUCCESS",
  UPDATE_FAILURE: "DATABASE_UPDATE_FAILURE",

  QUERY_REQUEST: "DATABASE_QUERY_REQUEST",
  QUERY_SUCCESS: "DATABASE_QUERY_SUCCESS",
  QUERY_FAILURE: "DATABASE_QUERY_FAILURE",

  DELETE_REQUEST: "DATABASE_DELETE_REQUEST",
  DELETE_SUCCESS: "DATABASE_DELETE_SUCCESS",
  DELETE_FAILURE: "DATABASE_DELETE_FAILURE",
};
